MONGO:
  local: true
  port: 27017
  address: "localhost"
  username: "root"
  password: "password"
  database: "server"
  rank-collection: "ranks"
  user-collection: "users"

REDIS:
  local: true
  port: 3306
  address: "localhost"
  username: "root"
  password: "password"

MESSAGES:
  rank-update: "&7Rank data for rank &a%rank_name% &7has been updated."